CourseCreator/src/uk/ac/lboro/coursecreator/model/Lesson.java
package uk.ac.lboro.coursecreator.model;

import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Lesson model bean.
 * 
 * @author Chris Matthews <C.Matthews2-09@student.lboro.ac.uk>
 */
public class Lesson {
	//the unique lesson ID number
	private int lessonId;
	
	//the title of the lesson
	@Size(min=3, max=80, message="Please enter between 3 and 80 characters.")
	private String lessonTitle;
	
	//HTML code containing lesson notes
	@NotEmpty(message="Please enter some notes for the lesson.")
	private String lessonNotes;
	
	//the YouTube ID of the lesson's video
	@NotEmpty(message="Please enter the YouTube URL for the lesson's video.")
	private String lessonVideoId;
	
	//HTML code containing a list of lesson objectives, can be empty
	private String lessonObjectives;
	
	//Basic constructor method
	public Lesson() {
		this.lessonId = 0;
		this.lessonTitle = "";
		this.lessonNotes = "";
		this.lessonVideoId = "";
		this.lessonObjectives = "";
	}
	
	/**
	 * Utility method to return a shorter version of the lesson notes for
	 * displaying on the front end.
	 * 
	 * @return	truncated lesson notes
	 */
	public String getShortLessonNotes() {
		String notes = lessonNotes;
		notes = notes.replaceAll("\\</p>", " ");
		notes = notes.replaceAll("\\</li>", " ");
		notes = notes.replaceAll("\\<.*?>","");
		
		if (notes.length() > 119) {
			return notes.substring(0, 116) + "...";
		} else {
			return notes;
		}
	}
	
	/**
	 * Utility method to return a shorter version of the lesson objectives
	 * for displaying on the front end.
	 * 
	 * @return	truncated lesson objectives
	 */
	public String getShortLessonObjectives() {
		String objs = lessonObjectives;
		objs = objs.replaceAll("\\</p>", " ");
		objs = objs.replaceAll("\\</li>", " ");
		objs = objs.replaceAll("\\<.*?>", "");
		
		if (objs.length() > 99) {
			return objs.substring(0, 96) + "...";
		} else {
			return objs;
		}
	}
	
	//Getters and setters
	public int getLessonId() {
		return lessonId;
	}
	public void setLessonId(int lessonId) {
		this.lessonId = lessonId;
	}
	public String getLessonTitle() {
		return lessonTitle;
	}
	public void setLessonTitle(String lessonTitle) {
		this.lessonTitle = lessonTitle;
	}
	public String getLessonNotes() {
		return lessonNotes;
	}
	public void setLessonNotes(String lessonNotes) {
		this.lessonNotes = lessonNotes;
	}
	public String getLessonVideoId() {
		return lessonVideoId;
	}
	public void setLessonVideoId(String lessonVideoId) {
		this.lessonVideoId = lessonVideoId;
	}
	public String getLessonObjectives() {
		return lessonObjectives;
	}
	public void setLessonObjectives(String lessonObjectives) {
		this.lessonObjectives = lessonObjectives;
	}
}

CourseCreator/WebContent/courseCreate.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core">
	<head jsf:id="head">
		
	</head>
	<body jsf:id="body">
		<ui:composition template="./template.xhtml">
		
		<ui:define name="title">Create Course Structure | CourseCreator</ui:define>
		
		<ui:define name="nav">
			<li class="list-heading active">Course Structure</li>
        	<li class="list-heading"><a href="index.jsf">Quit</a></li>
		</ui:define>
		
		<ui:define name="pageTitle">Create Course Structure</ui:define>
		
		<ui:define name="content">
			<p>
	        	Please use the form below to enter the Course Details for your Massive Open Online Course.  This structure allows 
	        	you to define details of the course administrator (or lecturer), the educational institution providing the course, 
	        	and the course itself.
        	</p>
        	
        	<form jsf:id="frmCreateCourse" enctype="multipart/form-data">
        		<fieldset>
        			<legend><h2>Administrator Details</h2></legend>
        			
        			<label jsf:for="txtAdministratorName">
        				<span>Administrator Name</span>
        				<input type="text" jsf:id="txtAdministratorName"  placeholder="e.g. Joe Bloggs" jsf:validator="#{validation.validateTextOnly}" jsf:value="#{courseAction.course.administratorName}"/>
        				<h:message for="txtAdministratorName" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtAdministratorEmail">
        				<span>Administrator Email</span>
        				<input type="email" jsf:id="txtAdministratorEmail" placeholder="e.g. joe.bloggs@email.com" jsf:value="#{courseAction.course.administratorEmail}"/>
        				<h:message for="txtAdministratorEmail" styleClass="alert-error"/>
        			</label>
        		</fieldset>
        		
        		<fieldset>
        			<legend><h2>Institution Details</h2></legend>
        			
        			<label jsf:for="txtInstitutionName">
        				<span>Institution Name</span>
        				<input type="text" jsf:id="txtInstitutionName" placeholder="e.g. Loughborough University" jsf:value="#{courseAction.course.institutionName}"/>
        				<h:message for="txtInstitutionName" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtInstitutionURL">
        				<span>Institution URL</span>
        				<input type="url" jsf:id="txtInstitutionURL" placeholder="e.g. http://www.lboro.ac.uk" jsf:validator="#{validation.validateURL}" jsf:value="#{courseAction.course.institutionURL}"/>
        				<h:message for="txtInstitutionURL" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtInstitutionLogo">
        				<span>Institution Logo<span class="note">(optional)</span></span>
        				<input type="file" jsf:id="txtInstitutionLogo" accept="image/x-png, image/png, image/gif, image/jpeg" jsf:validator="#{validation.validateInstitutionLogo}" jsf:value="#{courseAction.tempLogoImage}"/>
        				<h:message for="txtInstitutionLogo" styleClass="alert-error"/>
        			</label>
        		</fieldset>
        		
        		<fieldset>
        			<legend><h2>Course Details</h2></legend>
        			
        			<label jsf:for="txtCourseTitle">
        				<span>Course Title</span>
        				<input type="text" jsf:id="txtCourseTitle" placeholder="e.g. Advanced Human-Computer Interaction" jsf:value="#{courseAction.course.title}"/>
        				<h:message for="txtCourseTitle" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtCourseBlurb">
        				<span>Course Blurb</span>
        				<textarea jsf:id="txtCourseBlurb" rows="5" placeholder="e.g. This course covers core and advanced Human-Computer Interaction principles, focusing heavily on current and future interfaces." jsf:value="#{courseAction.course.blurb}"></textarea>
        				<h:message for="txtCourseBlurb" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtCourseStartDate">
        				<span>Course Start Date (dd/mm/yyyy)</span>
        				<input type="text" jsf:id="txtCourseStartDate" placeholder="e.g. 01/01/2014" jsf:validator="#{validation.validateDate}" jsf:value="#{courseAction.tempDate}"/>
        				<h:message for="txtCourseStartDate" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtCourseVideo">
        				<span>Introductory Video<span class="note">(optional)</span></span>
        				<input type="url" jsf:id="txtCourseVideo" placeholder="e.g. http://www.youtube.com/watch?v=Jwj2l3yl27E" jsf:validator="#{validation.validateCourseIntroVideo}" jsf:value="#{courseAction.tempIntroVid}"/>
        				<h:message for="txtCourseVideo" styleClass="alert-error"/>
        			</label>
        			
        			<label jsf:for="txtCourseForumURL">
        				<span>Course Forum URL<span class="note">(optional)</span></span>
        				<input type="url" jsf:id="txtCourseForumURL" placeholder="e.g. http://groups.google.com/forum/?fromgroups#!forum/course-builder-forum" jsf:validator="#{validation.validateOptionalURL}" jsf:value="#{courseAction.course.forumURL}"/>
        				<h:message for="txtCourseForumURL" styleClass="alert-error"/>
        			</label>
        		</fieldset>
        		
        		<h:messages style="display: none;"></h:messages>
        		
        		<fieldset>
        			<input type="submit" class="btn btn-primary" value="Create Course" jsf:action="#{courseAction.createCourse}"/>
					<input type="reset" class="btn" value="Clear Form"/>
        		</fieldset>
        	</form>
		</ui:define>
		
		</ui:composition>
	</body>
</html>

CourseCreator/WebContent/courseDetails.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">
	<head jsf:id="head">
		
	</head>
	<body jsf:id="body">
		<ui:composition template="./template.xhtml">
		
		<ui:define name="title">Course Details | CourseCreator</ui:define>
		
		<ui:define name="extraJs">
			<script jsf:name="js/tables.min.js"></script>
		</ui:define>
		
		<ui:define name="nav">
			<li class="list-heading" jsf:rendered="#{not empty courseAction.course.units}"><a href="export.jsf">Export Course</a></li>
			<li class="list-heading active"><a href="courseDetails.jsf">Course Details</a></li>
			<c:if test="#{not empty courseAction.course.units}">
			<li class="list-heading list-disabled">Units
				<ul id="unitNavList">
					<c:forEach items="#{courseAction.course.units}" var="unit">
						<li>
							<form jsf:id="frmMenu#{unit.unitId}" style="margin:0; padding:0;">
							<h:commandLink action="#{courseAction.showSelectedUnit}">
								<f:setPropertyActionListener target="#{courseAction.selectedUnit}" value="#{unit.unitId}"/>
								<h:outputText value="#{unit.unitId}. #{unit.title}"/>
							</h:commandLink>
							</form>
						</li>
					</c:forEach>
				</ul>
			</li>
			</c:if>
			
        	<li class="list-heading"><a href="index.jsf">Quit</a></li>
		</ui:define>
		
		<ui:define name="pageTitle">Review Course Details</ui:define>
		
		<ui:define name="content">
			<div class="key-info">
	        	<h2>Course Details</h2>
	        	<table class="table-horizontal table-double" jsf:id="tblCourseDetails">
		        	<tr>
		        		<th>Course Title: </th>
						<td class="wide"><h:outputText value="#{courseAction.course.title}"/></td>
						<th>Institution Name: </th>
		        		<td><h:outputText value="#{courseAction.course.institutionName}"/></td>
		        	</tr>
		        	<tr>
		        		<th>Course Blurb: </th>
		        		<td class="wide"><h:outputText value="#{courseAction.course.blurb}"/></td>
		        		<th>Institution Logo: </th>
		        		<td><h:graphicImage value="data:image/png;base64,#{courseAction.course.institutionLogo}" alt="logo" style="width:auto;max-height: 4em;"/></td>
		        	</tr>
		        	<tr>
		        		<th>Course Video: </th>
		        		<td class="wide"><h:outputLink value="http://youtube.com/watch?v=#{courseAction.course.introVideoId}"><h:outputText value="http://youtube.com/watch?v=#{courseAction.course.introVideoId}"/></h:outputLink></td>
		        		<th>Institution URL: </th>
		        		<td><h:outputLink value="#{courseAction.course.institutionURL}"><h:outputText value="#{courseAction.course.institutionURL}"/></h:outputLink></td>
		        	</tr>
		        	<tr>
		        		<th>Course Start Date: </th>
		        		<td class="wide"><h:outputText value="#{courseAction.course.startDate}"><f:convertDateTime type="date" pattern="dd/MM/yyyy"/></h:outputText></td>
		        		<th>Admin Name: </th>
		        		<td><h:outputText value="#{courseAction.course.administratorName}"/></td>
		        	</tr>
		        	<tr>
		        		<th>Course Forum URL: </th>
		        		<td class="wide"><h:outputLink value="#{courseAction.course.forumURL}"><h:outputText value="#{courseAction.course.forumURL}"/></h:outputLink></td>
		        		<th>Admin Email: </th>
		        		<td><h:outputText value="#{courseAction.course.administratorEmail}"/></td>
		        	</tr>
	        	</table>
	        	<h:link value="Edit Course" outcome="courseEdit" styleClass="btn btn-primary btn-small"/>
        	</div>
        	
        	<h2>Units &amp; Lessons</h2>
        	<form jsf:id="frmCourseDetails" style="margin-top: 0;">
	        	<h:link value="Import Unit PPTX" outcome="unitImport" styleClass="btn btn-primary btn-small"/>
	        	<h:link value="Create Unit from Scratch" outcome="unitCreate" styleClass="btn btn-small" style="margin-left: 1em;"/>
	        	<div class="alert-error" jsf:rendered="#{empty courseAction.course.units}">No units or lessons have been added yet.</div>
	        	<table class="table-vertical" jsf:rendered="#{not empty courseAction.course.units}">
	        		<thead>
	        			<tr>
	        				<th></th>
	        				<th>Unit #</th>
	        				<th>Unit Title</th>
	        				<th>Lessons</th>
	        				<th>Release Date</th>
	        				<th></th>
	        				<th></th>
	        			</tr>
	        		</thead>
	        		<tbody>
	        			<c:forEach items="#{courseAction.course.units}" var="unit">
	        				<tr>
	        					<td><a href="#" class="btn btn-small btn-inline" onclick="toggleChild($(this), $('#unit#{unit.unitId}-child')); return false;">&#43;</a></td>
	        					<td><h:outputText value="#{unit.unitId}"/></td>
	        					<td>
	        						<h:commandLink action="#{courseAction.showSelectedUnit}">
	        							<f:setPropertyActionListener target="#{courseAction.selectedUnit}" value="#{unit.unitId}"/>
	        							<h:outputText value="#{unit.title}"/>
	        						</h:commandLink>
	        					</td>
	        					<td><h:outputText value="#{unit.lessons.size()}"/></td>
	        					<td><h:outputText value="#{unit.releaseDate}"><f:convertDateTime type="date" pattern="dd/MM/yyyy"/></h:outputText></td>
	        					<td>
	        						<h:commandLink action="#{courseAction.showSelectedUnit}" styleClass="btn btn-small btn-inline">
	        							<f:setPropertyActionListener target="#{courseAction.selectedUnit}" value="#{unit.unitId}"/>
	        							Edit
	        						</h:commandLink>
	        					</td>
	        					<td>
	        						<h:commandLink action="#{courseAction.deleteSelectedUnit}" styleClass="btn btn-small btn-inline" onclick="if(!confirm('Do you really want to delete #{unit.title}?')) { return false; }">
	        							<f:setPropertyActionListener target="#{courseAction.selectedUnit}" value="#{unit.unitId}"/>
	        							Delete
	        						</h:commandLink>
	        					</td>
	        				</tr>
	        				<c:if test="#{unit.lessons.size() > 0}">
	        					<tr class="child-row" id="unit#{unit.unitId}-child">
	        						<td></td>
	        						<td colspan="6">
	        							<table class="table-vertical">
	        								<thead>
	        									<tr>
	        										<th>Lesson #</th>
	        										<th>Lesson Title</th>
	        										<th>Lesson Notes</th>
	        										<th>Lesson Video</th>
	        									</tr>
	        								</thead>
	        								<tbody>
	        									<c:forEach items="#{unit.lessons}" var="lesson">
	        										<tr>
	        											<td><h:outputText value="#{lesson.lessonId}"/></td>
	        											<td><h:outputText value="#{lesson.lessonTitle}"/></td>
	        											<td><h:outputText value="#{lesson.shortLessonNotes}"/></td>
	        											<td>
	        												<a class="img-link" href="http://www.youtube.com/watch?v=#{lesson.lessonVideoId}">
	        												<img src="http://img.youtube.com/vi/#{lesson.lessonVideoId}/hqdefault.jpg" height="45" width="70" alt="#{lesson.lessonTitle}"/>
	        												</a>
	        											</td>
	        										</tr>
	        									</c:forEach>
	        								</tbody>
	        							</table>
	        						</td>
	        					</tr>
	        				</c:if>
	        			</c:forEach>
	        		</tbody>
	        	</table>
        	</form>
		</ui:define>
		
		</ui:composition>
	</body>
</html>

CourseCreator/WebContent/courseImport.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">
	<head jsf:id="head">
		
	</head>
	<body jsf:id="body">
		<ui:composition template="./template.xhtml">
		
		<ui:define name="title">Import Course from PowerPoint | CourseCreator</ui:define>
		
		<ui:define name="extraJs">
			
		</ui:define>
		
		<ui:define name="nav">
			<li class="list-heading active">Import Course</li>
        	<li class="list-heading"><a href="index.jsf">Quit</a></li>
		</ui:define>
		
		<ui:define name="pageTitle">Import Course from PowerPoint</ui:define>
		
		<ui:define name="content">
			<p>
	        	Please upload your Course Structure presentation file using the form below.  For details on how to structure this file, please <a href="#" target="_blank">click here</a>.
        	</p>
        	<form jsf:id="frmImportStructure" enctype="multipart/form-data">
        		<fieldset>
        			<legend><h2>Upload PowerPoint (.pptx) Course Structure</h2></legend>
        			
        			<label jsf:for="txtCoursePowerPoint">
        				<span>PowerPoint File</span>
        				<input type="file" jsf:id="txtCoursePowerPoint" accept="application/vnd.openxmlformats-officedocument.presentationml.presentation" jsf:validator="#{validation.validatePowerPointFile}" jsf:value="#{courseAction.tempCoursePptx}"/>
        				<h:message for="txtCoursePowerPoint" styleClass="alert-error"/>
        			</label>
        		</fieldset>
        		
        		<h:messages style="display: block;"></h:messages>
        		
        		<fieldset>
        			<input type="submit" class="btn btn-primary" value="Create Course" jsf:action="#{courseAction.importCoursePptx}"/>
					<input type="reset" class="btn" value="Clear Form"/>
        		</fieldset>
        	</form>
		</ui:define>
		
		</ui:composition>
	</body>
</html>

CourseCreator/WebContent/export.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">
	<head jsf:id="head">
		
	</head>
	<body jsf:id="body">
		<ui:composition template="./template.xhtml">
		
		<ui:define name="title">Export Course | CourseCreator</ui:define>
		
		<ui:define name="extraJs">
			
		</ui:define>
		
		<ui:define name="nav">
			<li class="list-heading active"><a href="courseDetails.jsf">Course Details</a></li>
			<c:if test="#{not empty courseAction.course.units}">
			<li class="list-heading list-disabled">Units
				<ul id="unitNavList">
					<c:forEach items="#{courseAction.course.units}" var="unit">
						<li>
							<form jsf:id="frmMenu#{unit.unitId}" style="margin:0; padding:0;">
							<h:commandLink action="#{courseAction.showSelectedUnit}">
								<f:setPropertyActionListener target="#{courseAction.selectedUnit}" value="#{unit.unitId}"/>
								<h:outputText value="#{unit.unitId}. #{unit.title}"/>
							</h:commandLink>
							</form>
						</li>
					</c:forEach>
				</ul>
			</li>
			</c:if>
			
        	<li class="list-heading"><a href="index.jsf">Quit</a></li>
		</ui:define>
		
		<ui:define name="pageTitle">Export to Google CourseBuilder</ui:define>
		
		<ui:define name="content">
			<p>
	        	Please download the files below and place these in your CourseBuilder installation directory, replacing any existing files.
        	</p>
        	<form jsf:id="frmExport">
        		<fieldset>
        			<legend><h2>Download CourseBuilder Files</h2></legend>
        			
        			<label>
        				<span>course.yaml</span>
        				<h:commandLink styleClass="btn btn-primary" action="#{courseAction.exportCourseYaml}">Download</h:commandLink>
        			</label>
        			
        			<label>
        				<span>course_template.yaml</span>
        				<h:commandLink styleClass="btn btn-primary" action="#{courseAction.exportCourseTemplateYaml}">Download</h:commandLink>
        			</label>
        			
        			<label>
        				<span>data/unit.csv</span>
        				<h:commandLink styleClass="btn btn-primary" action="#{courseAction.exportUnitCsv}">Download</h:commandLink>
        			</label>
        			
        			<label>
        				<span>data/lesson.csv</span>
        				<h:commandLink styleClass="btn btn-primary" action="#{courseAction.exportLessonCsv}">Download</h:commandLink>
        			</label>
        		</fieldset>
        		
        		<h:messages style="display: none;"></h:messages>
        	</form>
		</ui:define>
		
		</ui:composition>
	</body>
</html>

CourseCreator/WebContent/unitDetails.xhtml
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:jsf="http://xmlns.jcp.org/jsf" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core">
	<head jsf:id="head">
		
	</head>
	<body jsf:id="body">
		<ui:composition template="./template.xhtml">
		
		<ui:define name="title">Unit Details | CourseCreator</ui:define>
		
		<ui:define name="extraJs">
			<script jsf:name="js/tables.min.js"></script>
		</ui:define>
		
		<ui:define name="nav">
			<li class="list-heading"><a href="courseDetails.jsf">Course Details</a></li>
			<c:if test="#{not empty courseAction.course.units}">
			<li class="list-heading list-disabled active">Units
				<ul id="unitNavList">
					<c:forEach items="#{courseAction.course.units}" var="unit">
						<li>
							<form jsf:id="frmMenu#{unit.unitId}" style="margin:0; padding:0;">
							<h:commandLink action="#{courseAction.showSelectedUnit}">
								<f:setPropertyActionListener target="#{courseAction.selectedUnit}" value="#{unit.unitId}"/>
								<h:outputText value="#{unit.unitId}. #{unit.title}"/>
							</h:commandLink>
							</form>
						</li>
					</c:forEach>
				</ul>
			</li>
			</c:if>
			
        	<li class="list-heading"><a href="index.jsf">Quit</a></li>
		</ui:define>
		
		<ui:define name="pageTitle">Review Unit Details</ui:define>
		
		<ui:define name="content">
			<div class="key-info">
	        	<h2>Unit Details</h2>
	        	<form jsf:id="frmUnitDtls" style="margin: 0;">
	        	<table class="table-horizontal table-single" jsf:id="tblUnitDetails">
		        	<tr>
		        		<th>Unit ID: </th>
						<td><h:outputText value="#{courseAction.currentUnit.unitId}"/></td>
		        	</tr>
		        	<tr>
		        		<th>Unit Title: </th>
		        		<td><h:outputText value="#{courseAction.currentUnit.title}"/></td>
		        	</tr>
		        	<tr>
		        		<th>Release Date: </th>
		        		<td><h:outputText value="#{courseAction.currentUnit.releaseDate}"><f:convertDateTime type="date" pattern="dd/MM/yyyy"/></h:outputText></td>
		        	</tr>
	        	</table>
	        	<h:commandLink action="#{courseAction.editCurrentUnit}" styleClass="btn btn-primary btn-small">Edit Unit</h:commandLink>
	        	</form>
        	</div>
        	
        	<h2>Lessons</h2>
        	<form jsf:id="frmUnitDetails" style="margin-top: 0;">
	        	<h:link value="Add Lesson" outcome="lessonCreate" styleClass="btn btn-primary btn-small"/>
	        	<div class="alert-error" jsf:rendered="#{empty courseAction.currentUnit.lessons}">No lessons have been added yet.</div>
	        	<table class="table-vertical" jsf:rendered="#{not empty courseAction.currentUnit.lessons}">
	        		<thead>
	        			<tr>
	        				<th>Lesson #</th>
	        				<th>Lesson Title</th>
	        				<th>Lesson Notes</th>
	        				<th>Lesson Objectives</th>
	        				<th>Lesson Video</th>
	        				<th></th>
	        				<th></th>
	        			</tr>
	        		</thead>
	        		<tbody>
	        			<c:forEach items="#{courseAction.currentUnit.lessons}" var="lesson">
	        				<tr>
	        					<td><h:outputText value="#{lesson.lessonId}"/></td>
	        					<td style="text-align:left;"><h:outputText value="#{lesson.lessonTitle}"/></td>
	        					<td><h:outputText value="#{lesson.shortLessonNotes}" escape="false"/></td>
	        					<td><h:outputText value="#{lesson.shortLessonObjectives}" escape="false"/></td>
	        					<td>
	        						<a class="img-link" href="http://www.youtube.com/watch?v=#{lesson.lessonVideoId}">
									<img src="http://img.youtube.com/vi/#{lesson.lessonVideoId}/hqdefault.jpg" height="45" width="70" alt="#{lesson.lessonTitle}"/>
									</a>
	        					</td>
	        					<td>
	        						<h:commandLink action="#{courseAction.editSelectedLesson}" styleClass="btn btn-small btn-inline">
	        							<f:setPropertyActionListener target="#{courseAction.selectedLesson}" value="#{lesson.lessonId}"/>
	        							Edit
	        						</h:commandLink>
	        					</td>
	        					<td>
	        						<h:commandLink action="#{courseAction.deleteSelectedLesson}" styleClass="btn btn-small btn-inline">
	        							<f:setPropertyActionListener target="#{courseAction.selectedLesson}" value="#{lesson.lessonId}"/>
	        							Delete
	        						</h:commandLink>
	        					</td>
	        				</tr>
	        			</c:forEach>
	        		</tbody>
	        	</table>
        	</form>
		</ui:define>
		
		</ui:composition>
	</body>
</html>